### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.3.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [CarstenKarbach/MoTAC#3]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.3.

**Comment by CarstenKarbach** [comment]
Dear locutis-of-borg-1999,
I have not created the entry for MoTAC on F-Droid. I do not know how to edit or contribute to F-Droid pages. Could you specify, on which page exactly a Changelog link would be helpful? I suggest to open a ticket on https://gitlab.com/fdroid/fdroiddata/issues. As Changelog link you could probably use https://github.com/CarstenKarbach/MoTAC/commits/motacmaster

Best regards,

Carsten

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by CarstenKarbach** [comment]
I guess, I do not have a changelog except for the commit log. That is why I cannot fix this issue.
